### ISSUE TITLE
Left "…Empty call stack\n" on fail

### ISSUE THREAD

**Issue by Profpatsch** [GaloisInc/cereal#34]
I get a strange error on fail, even in the most trivial cases:

```
data Test = Test { someVal :: ByteString } deriving (Show, Generic)
instance Serialize Test where
  get = fail "test"

testtest :: Either String Test
testtest = decode "B6034fooobaarbazbla"
```

Output: `Left "Failed reading: test\nEmpty call stack\n"`

**Comment by elliottt** [comment]
The error that it's producing includes your "test" message from the use of `fail` in the `Serialize` instance, as well as indicating that the error stack was empty.  The error stack can be specified through uses of the `label` function, which is analogous to the `<?>` function from parsec and attoparsec.  If you change your implementation of `get` to:

```haskell
instance Serialize Test where
  get = label "Test" (fail "test")
```

you'll see that the "Empty call stack" message changes into a single line with "Test" on it.

Maybe the issue here is that the error message is just a little weird, and we should produce an error value that looks more like this:

```haskell
data Error = Error String [String]
```

Which includes the error message, as well as all of the labels above it, but doesn't prescribe any formatting.

**Comment by Profpatsch** [comment]
Ah! I suppose a bit of documentation would help, too. :)

Actually, you could just copy that comment to the source!

**Comment by Profpatsch** [comment]
That must be the problem to my current problem, too. I’ve got a `Get` parser done, but it consumes more bytes than are available; so probably I just have to label everything and it will point me to the location where `get` fails.

Is there an actual example of something like that being used?

**Comment by elliottt** [comment]
I use the `label` stuff extensively in (HaNS)[https://github.com/galoisinc/hans], specifically in the (Hans.Message)[https://github.com/GaloisInc/HaNS/tree/master/src/Hans/Message] hierarchy.

In order to avoid confusion in the future, I think that changing the result type of the `Get` monad from `Either String a` to `Either Error a`, where `Error` is a pair of the message and label stack, would be sensible.  I think that may start down a path to address #26 as well.

**Comment by elliottt** [comment]
Given that this has been inactive for over a year, I'm going to close it :)
