### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by coot** [GaloisInc/cereal#81]
When I build `cereal-0.5.7.0` with `ghc844` I get a compiler error:
```
src/Data/Serialize.hs:290:9: warning: [-Wincomplete-patterns]
    Pattern match(es) are non-exhaustive
    In an equation for ‘findNr’: Patterns not matched: _ _
    |
290 |         findNr lo hi
    |         ^^^^^^^^^^^^...
[1 of 4] Compiling Data.Serialize.Get ( src/Data/Serialize/Get.hs, dist/build/Data/Serialize/G
et.p_o )
[2 of 4] Compiling Data.Serialize.Put ( src/Data/Serialize/Put.hs, dist/build/Data/Serialize/P
ut.p_o )
[3 of 4] Compiling Data.Serialize.IEEE754 ( src/Data/Serialize/IEEE754.hs, dist/build/Data/Ser
ialize/IEEE754.p_o )
[4 of 4] Compiling Data.Serialize   ( src/Data/Serialize.hs, dist/build/Data/Serialize.p_o )

src/Data/Serialize.hs:290:9: warning: [-Wincomplete-patterns]
    Pattern match(es) are non-exhaustive
    In an equation for ‘findNr’: Patterns not matched: _ _
    |
290 |         findNr lo hi
    |         ^^^^^^^^^^^^...
Preprocessing test suite 'test-cereal' for cereal-0.5.7.0..
Building test suite 'test-cereal' for cereal-0.5.7.0..
[1 of 3] Compiling GetTests         ( tests/GetTests.hs, dist/build/test-cereal/test-cereal-tm
p/GetTests.o )
[2 of 3] Compiling RoundTrip        ( tests/RoundTrip.hs, dist/build/test-cereal/test-cereal-t
mp/RoundTrip.o )

tests/RoundTrip.hs:33:12: error:
    • The constructor ‘Success’ should have 6 arguments, but has been given 3
    • In the pattern: Success _ _ _
      In an equation for ‘RoundTrip.isSuccess’:
          RoundTrip.isSuccess (Success _ _ _) = True
   |
33 | isSuccess (Success _ _ _) = True
   |            ^^^^^^^^^^^^^
```

**Comment by DanBurton** [comment]
Bump. I'm seeing this build failure when building the test suite from the latest tarball on hackage: cereal-0.5.7.0. I'll mark it as an expected test failure in Stackage until a new, working tarball is released.

**Comment by DanBurton** [comment]
I was able to reproduce this locally like so:

```bash
stack unpack cereal-0.5.7.0 && cd cereal-0.5.7.0
echo 'resolver: nightly-2018-12-22' > stack.yaml
stack build --test --bench --no-run-benchmarks --fast
```

**Comment by qrilka** [comment]
@DanBurton I couldn't find `cereal` in Stackage `build-constraints.yaml` but in the snapshot of LTS-13.0 I see `tests: expect-failure`. Also I think it should go into section `skipped-tests` as tests fail to get build and not fail when being run.

**Comment by DanBurton** [comment]
>  I couldn't find cereal in Stackage build-constraints.yaml

It is implicitly included due to being a dependency of some other stuff in Stackage. (Tangentially, see https://github.com/commercialhaskell/stackage/issues/4158#issuecomment-440767408)

I'm not entirely sure why it does not show up under the `expected-test-failures` section of build-constraints.yaml currently; it probably should.

> I think it should go into section skipped-tests as tests fail to get build and not fail when being run.

The category of `expect-failure` is used for both build and test run failures. `skipped-tests` is only used to avoid pulling in a package's test suite dependencies. By being in `expect-failure` instead of `skipped-tests`, we assert that, at the very least, the package's test suite dependency version bounds are compatible with the versions of those dependencies found in the build plan.

We _could_ arguably create separate categories for `expect-test-build-failure` and `expect-test-run-failure`, but there has not yet been a compelling reason for us to do so. There is, at least, a commented section of the list for compilation failures. See: https://github.com/commercialhaskell/stackage/blob/b60bda1417863c4025bbd34dabf4d996d90c2271/build-constraints.yaml#L4506

**Comment by qrilka** [comment]
Thanks for the explanation

**Comment by ivanbrennan** [comment]
Why was this issue closed? The commit that claims to have fixed it (https://github.com/GaloisInc/cereal/commit/00ea19fc1221e3859a18b4efcf106ac2f6247ef1) doesn't appear to address the problem. @glguy Am I missing something?

It looks like a trivial fix, e.g.
```diff
diff --git a/src/Data/Serialize.hs b/src/Data/Serialize.hs
index 8140def..7f355c1 100644
--- a/src/Data/Serialize.hs
+++ b/src/Data/Serialize.hs
@@ -291,7 +291,7 @@ nrBits k =
         findNr lo hi
             | mid == lo = hi
             | 2 ^ mid <= k = findNr mid hi
-            | 2 ^ mid > k  = findNr lo mid
+            | otherwise    = findNr lo mid
          where mid = (lo + hi) `div` 2
     in findNr (expMax `div` 2) expMax
```
Should I make a PR with the above change?

**Comment by glguy** [comment]
@ivanbrennan The issue was closed because the test suite currently builds and passes. I can make the change above to remove the warning, but that's not related to this issue as far as I know.

**Comment by ivanbrennan** [comment]
@glguy Thanks for clarifying. I think the test suite builds and passes because it's not treating compiler warnings as errors.

I ran into this when attempting to build a project that depends on `cereal-0.5.8.1`, using
```
cabal v2-build --ghc-option=-Werror
```

When cabal built `cereal` it treated the compiler warning as an error. I think it would make sense to treat warnings as errors in the test suite, like:
```diff
diff --git a/.travis.yml b/.travis.yml
index 53df4fb..95fd33c 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -74,7 +74,7 @@ install:
 script:
  - if [ -f configure.ac ]; then autoreconf -i; fi
  - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
- - cabal build   # this builds all libraries and executables (including tests/benchmarks)
+ - cabal build --ghc-option=-Werror  # this builds all libraries and executables (including tests/benchmarks)
  - cabal test
  - cabal sdist   # tests that a source-distribution can be generated
```
And perhaps `-Wall` as well?

**Comment by glguy** [comment]
No, I don't think it's a good idea to treat warnings as errors in a context other than when you're building your own project. Dependencies having warnings should definitely not break another project's build.

**Comment by ivanbrennan** [comment]
Fair enough. Building in CI with `-Werror` is a practice I've gotten into at work, but maybe it doesn't make sense for open source projects. Looking at some other well-established libraries I don't see them using it either. Live and learn!
